### ISSUE TITLE
What projects use eslint-config-peopledoc?

### ISSUE THREAD

**Issue by edouard-lopez** [peopledoc/eslint-config-peopledoc#11]
List of projects using this config.

**Comment by hugurp** [comment]
@amessinger, I assume this is now a standard at peopledoc?

Included in ember-pdui https://github.com/peopledoc/ember-peopledoc-ui/blob/master/package.json#L65

**Comment by edouard-lopez** [comment]
Awesome :smile: 

@hugurp be aware that we removed the listing of related project based on feedback and security concern ping @xcambar
