### ISSUE TITLE
Investigate eslint-plugin-ember

### ISSUE THREAD

**Issue by edouard-lopez** [peopledoc/eslint-config-peopledoc#17]
EmberFest talk mentioned [eslint-plugin-ember](https://github.com/ember-cli/eslint-plugin-ember). 
Need to investigate to see what's overlapping with suave and if it's useful for us.

**Comment by edouard-lopez** [comment]
`eslint-plugin-ember-suave` has only [5 rules](https://github.com/DockYard/eslint-plugin-ember-suave/tree/master/lib/rules), one [not documented](https://github.com/DockYard/eslint-plugin-ember-suave/tree/master/docs/rules) and only few of them related to Ember as you pointed out.

We can either replace `eslint-plugin-ember-suave` by `eslint-plugin-ember` or use them together.

**Comment by xcambar** [comment]
Any recommendation?

**Comment by edouard-lopez** [comment]
For example, if we use both we can disable rules we don't want in our [`ember.js` config](https://github.com/peopledoc/eslint-config-peopledoc/blob/master/ember.js):

```js

module.exports = {
  …
  extends: [
    "eslint:recommended", 
    "plugin:ember-suave/recommended", 
    "plugin:ember/recommended",
    "./core.js"
  ],
  rules: {
    'ember-suave/require-access-in-comments': 'off'
  }
};
```

**Comment by xcambar** [comment]
I'm fine with introducing eslint-plugin-ember alongside suave, but lets' wait for more comment...

**Comment by saintsebastian** [comment]
@edouard-lopez Those two are the ones I also thought about. While I think I'd prefer having them, they are completely taste-based in my opinion, but since most of Ember applications are written with those in place, I'd rather they stay for consistency.

**Comment by BlueCutOfficial** [comment]
When upgrading Ember to 2.18.0, `eslint-plugin-ember` is present by default in the devDependencies.

**Comment by hugurp** [comment]
Is this still actual?

It seems both are acutally present in the package.json on master: cf https://github.com/peopledoc/eslint-config-peopledoc/blob/master/package.json#L8

Maybe we close this issue as the tribe seems satisfied?

**Comment by edouard-lopez** [comment]
@hugurp @GreatWizard introduced the change to the _package.json_ and the _ember config_ as per 637f5492ce7c2d2c95c6514c946f4f478990eda9. 
Currently you're using recommend rules from both `eslint-plugin-ember` and `eslint-plugin-ember-suave`, for [more info read my comment](https://github.com/peopledoc/eslint-config-peopledoc/issues/17#issuecomment-366932384)
