### ISSUE TITLE
Prefer destructuring for ember properties with curly multiline

### ISSUE THREAD

**Issue by GreatWizard** [peopledoc/eslint-config-peopledoc#20]
Currently both syntax are correct:

```js
const { Router: EmberRouter } = Ember;
```

```js
const {
  Router: EmberRouter
} = Ember;
```

As talk on slack, **the second syntax** seems to be the most "clearer" to see what is available.
I create this issue to see how to configure our own rules to make it possible with eslint to lint correctly.

Useful resources:
- https://eslint.org/docs/rules/object-curly-newline
- https://eslint.org/docs/rules/prefer-destructuring
- https://github.com/DockYard/eslint-plugin-ember-suave/blob/master/lib/rules/require-const-for-ember-properties.js

**Comment by hugurp** [comment]
For this I also appreciate the `{ "consistent": true }`.

Any updates on wishes for that?

I'd gladly implement whatever solution is decided for.

**Comment by MrChocolatine** [comment]
After nearly 4 years, looks like we can close this issue.

It has been deleted in version 2:
https://github.com/DockYard/eslint-plugin-ember-suave/compare/v1.0.0...v2.0.0

See also:
https://github.com/DockYard/eslint-plugin-ember-suave/pull/70
