### ISSUE TITLE
Always a space after `function` keyword

### ISSUE THREAD

**Issue by ryuran** [peopledoc/eslint-config-peopledoc#56]
I propose this rule to identify clearly anonymous function and keep it consistent.

OK :
```
function () { /*…*/ }
function notAnonymous() { /*…*/ }
async () => { /*…*/ }
```

KO :
```
function() { /*…*/ }
async() => { /*…*/ }
```

```
    'space-before-function-paren': ['error', {
      anonymous: 'always',
      named: 'never',
      asyncArrow: 'always'
    }],
```

**Comment by MrChocolatine** [comment]
Relates to #39 .

**Comment by MrChocolatine** [comment]
+1 to the proposition. Whitespace are good and not evil.

**Comment by Pixelik** [comment]
I don't want to have to remember of this small difference while I code:

```
function ()
function something()
```

**Comment by MrChocolatine** [comment]
It helps identifying anonymous and named functions.

Also, with our current recommendations, something contradictory regarding generator functions:

```js
function* myfunc() {} // Valid

let myfunc = function* () {} // Valid. Space required, but why this time hum?

let myfunc = function*() {} // The linter complains for a missing space
```

**Comment by ryuran** [comment]
@Pixelik I don't see any difference if in my mind the rule is "always a space after `function`" or "always a space before the function name even if it is missing"

If name is missing the space mark the difference between the name and the `function` keyword.
This rules make anonymous function more identifiable.

I can't and I don't want remember every lint rules. It's why I use tools to check and fix it.
Like me you can use a formatter or `eslint --fix` command to manage it.

So "I don't want to have to remember" is not really an argument.

We only need a rule to follow to keep the code consistent.

Valid argument pro:
- easier to identify anonymous function 
- easier to found anonymous function (research `function (` works)
- consistent with generator function rules

Valid argument cons:
- …
