### ISSUE TITLE
./base.js

### ISSUE THREAD

**Issue by ryuran** [peopledoc/eslint-config-peopledoc#58]
https://github.com/peopledoc/eslint-config-peopledoc/blob/0677b702ee22f7cd2c327cda89e69dba46051ec2/prettier.js#L5
prettier config do a reference to a missing `./base.js`.
Should it be `./core.js` ?

**Comment by edouard-lopez** [comment]
Hello @ryuran, You are probably correct, in my souvenir I wrote the prettier config in order to be forward-compatibility but I don't remember it being used when I left.

Best to check with the team, it was a few years back for me :)
